### PR TITLE
Added NODE_OPTIONS environment

### PR DESCRIPTION
**Pull request by supermock**
Added TOOL_NODE_FLAGS environment, for add node flags.

Important for more configurations, example: --max_old_space_size

### CODE REVIEW

**Comment by abernix** [comment]
This certainly isn't the right environment variable.  `TOOL_NODE_FLAGS` is for the `meteor` command line tool, which is not involved here at all! You might have meant `NODE_OPTIONS`?  If so, that's reasonable, but please submit the change to this PR.

**Comment by supermock** [comment]
Already changed with request.
@abernix

**Comment by smeijer** [comment]
supporting `TOOL_NODE_FLAGS` would be most welcome for the build process though. See #35

**Comment by abernix** [comment]
I've changed the variable (again!) to `METEORD_NODE_OPTIONS` to avoid a namespace conflict with the now Node.js-supported (as of v8.0.0) `NODE_OPTIONS` support.  See my commit message for more information: https://github.com/abernix/meteord/pull/15/commits/a761fc8cc4f6c195498bc2d3f17af75bcce2d075.

**Comment by abernix** [comment]
This is now published in the latest `abernix/meteord:node-8*` tags, seen here: https://hub.docker.com/r/abernix/meteord/.  Please test and let me know if it works!

**Pull request merged**
