### PR TITLE
Node 12.18.4

### PR DESCRIPTION
**Pull request by emjimadhu**
This PR has following

Meteor **1.11.1**
Node **12.18.4**

you can use the Docker image from here [https://hub.docker.com/repository/docker/emjimadhu/meteord](https://hub.docker.com/repository/docker/emjimadhu/meteord)

### CODE REVIEW

**Comment by maxfi** [comment]
@emjimadhu Now that [Meteor v1.11.1](https://github.com/meteor/meteor/blob/devel/History.md#v1111-2020-09-16) has been updated to use node to v12.18.4 maybe this can be updated in your PR? Thanks!

**Comment by emjimadhu** [comment]
> @emjimadhu Now that [Meteor v1.11.1](https://github.com/meteor/meteor/blob/devel/History.md#v1111-2020-09-16) has been updated to use node to v12.18.4 maybe this can be updated in your PR? Thanks!

Done! this PR is update for Meteor 1.11.1 and Node 12.18.4 and the Docker images are also updated. Thanks

**Comment by maxfi** [comment]
Any chance we could get this merged @abernix and pushed to Docker Hub? Would be really helpful for people using https://github.com/zodern/meteor-up. Realise you're probably super busy so thanks heaps in advance! 🙏 🙏 🙏

**Comment by eugle** [comment]
It feels like the author gave up

**Comment by mtwalsh** [comment]
Still early days in my testing but this image (`zodern/meteor`) seems to be working fine so far with Meteor 1.12 and it automatically uses the correct Node.js and npm versions:

https://github.com/zodern/meteor-docker

**Comment by abernix** [comment]
I've published new images with Node.js 12.20.0 and Meteor 1.12.

**Comment by wvanooijen92** [comment]
@abernix Thank you! But I am a bit confused. It seems like meteor's node version is v12.18.4 for meteor v1.12 and v12.20.1 for meteor v1.12.1


```
$ meteor --version
Meteor 1.12

$ meteor node -v
v12.18.4
```

```
$ meteor --version
Meteor 1.12.1

$ meteor node -v
v12.20.1
```

With 12.20.0 I am unable to deploy. I get a "invalid ELF header" error, also described here https://github.com/veliovgroup/Meteor-Files/issues/781

I may be mistaken but to be able to test v12.18.4 and 12.20.1 would be great.

**Pull request closed without merging**
